version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/myclinic
    ports:
      - 3000:3000
    image: app:myclinic-app
    container_name: myclinic_container
    command: yarn start
