import mock from './mock'

import './jwt'
import './select'
import './pages/faq'
import './apps/invoice'
import './apps/calendar'
import './apps/userList'
import './apps/patientList'
import './pages/profile'
import './pages/blog-data'
import './tables/datatables'
import './pages/pricing-data'
import './navbar/navbarSearch'
import './pages/knowledge-base'
import './apps/permissionsList'
import './cards/card-analytics'
import './cards/card-statistics'
import './pages/account-settings'
import './autoComplete/autoComplete'
import './myClinic/encounter'

mock.onAny().passThrough()
